### ISSUE TITLE
help needed with federation + pubsub, any suggestions?

### ISSUE THREAD

**Issue by jokeyrhyme** [capriza/node-busmq#30]
I have the following federated pubsub setup:
- https://gist.github.com/jokeyrhyme/61862f6370088ce1b2643a1877e8bc89

I'm using Node.js v5.10.1.

With the code as-is, both server and client output both the date messages (published by the server) and the "ping" messages (published by the client).

If I swap the comments around so that the client is connecting via federation, the console messages indicate that federation and subscription are successful (as before). However, the server no longer outputs the client's "ping" messages, and the client no longer outputs the server's date messages.

I've also got a similar browser version of the client, and I'm seeing the same problem: federation appears to initialise properly, but the bus in the client is completely disconnected from the bus in the server.

Any ideas about how I'm doing this wrong?

**Comment by fujifish** [comment]
You found a bug, I'll fix it soon.

**Comment by fujifish** [comment]
I committed the fix. It was a **big** bug and required some heavy changes. 
The biggest change was that I had to remove from the `.publish()` callback the number of subscribers that received the message. Now the callback only gets an `err` parameter if there was an error.

The reason for this change is because busmq does't open separate connections to redis for each subscriber. It uses a single connection to manage all subscribers flowing through it. In that sense, redis is only aware of one subscriber, and busmq distributes the message to all internal subscribers.

I tried this with the code you provided in the gist and it works.

I'd appreciate it if you could test it out and let me know.

**Comment by jokeyrhyme** [comment]
@fujifish woah: a response and an actual fix in just a few hours. Most impressive. :D
I'll definitely look at this today, and will let you know how I'm getting along.

My pubsub use case may involve 10 - 100 WebSocket clients, across 1 - 3 BusMQ workers, all directly using the same Redis cluster. Everything I've read makes me think BusMQ is the perfect solution for this, so I'm very keen to see this working. :) Thanks!

**Comment by jokeyrhyme** [comment]
Oh, just one little thing: would it be possible for you to start adding git tags that match npm versions? No need to do this for previous versions, but maybe consider it for future releases? I've found it useful for debugging, or comparing changes. Cheers!

**Comment by jokeyrhyme** [comment]
@fujifish success! 1.5.0 fixes it all for me. I have Node.js, Chrome and Firefox clients, all successfully seeing all expected messages across a federated pubsub. Yay! Thanks!
