### ISSUE TITLE
missing events in the browser / federated pubsub

### ISSUE THREAD

**Issue by jokeyrhyme** [capriza/node-busmq#31]
I have a browser client:
- https://github.com/blinkmobile/no-polling-example/blob/c1c68ee02202783a1451b9d8d0e9e62586099ffd/www/bus.js

pubsub via federation is working excellently. And I can terminate the server, bring it back up again, and the client will reconnect automatically. I see the "event = subscribed" log entry in my browser whenever the subscription is (re)established. Excellent!

As you can see from the code, I've also attached loggers to the "online", "offline" and "error" events on the bus, and to the "error" event on the pubsub. None of these are ever triggered in the browser as far as my testing goes, even when I terminate the server.

I do see the following WebSocket errors in the browser console, however:

> WebSocket connection to 'ws://docker.local:3000/bus/federated?secret=mysecret' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

But my error handlers don't get triggered, so my code has no opportunity to react to such things.

I really appreciate the hard work that has gone into this library. Am I using the event APIs in a weird way here? Or hooking them too late or something?

**Comment by fujifish** [comment]
`online`/`offline` events will not be triggered for federated objects since you are not actually connecting to the bus in federated mode. These events are triggered for indicating the connection state to _redis_.

I've setup for federated objects to receive `reconnecting` and `reconnected` events when the websocket connection is broken and re-established, so attach them directly to the pubsub object. 

Use the latest busmq.js/busmq.min.js I released and let me know how it works.

**Comment by jokeyrhyme** [comment]
I've made the following changes:
- https://github.com/blinkmobile/no-polling-example/commit/ea3afaea965785da3b6b213e483afea7f8c56eae

However, I'm not seeing `reconnecting` or `reconnected` events from the federated pubsub object. I do see `subscribed` events at the beginning, and right after the WebSocket is re-established (after an outage).

Thanks so much for your help here. I should add that this is not urgent for me.

I have figured out a work-around (not in my code yet) using heartbeat events. If we can assume a heartbeat event every 5 seconds or 15 seconds or w/e, then we can set a timer after each one. If we don't get a heartbeat event when it is expected, we assume the connection is faulty. So we can simulate a "disconnected" event for use cases where this is necessary.

**Comment by fujifish** [comment]
I've made some more tests and found the problem, I'll try to explain.

Inherently, all methods invoked on the federated object (in this case the pubsub object) get delivered to the remote bus location instead of being invoked locally. Federation events (ready, reconnecting, ...) are exposed on a different object which wraps the pubsub object, however I did not expose the federating object in the browser. 

I've release version 1.5.1 which adds the federating object as a member to the pubsub object so you can attach listeners to it.

Change the line:
```javascript
pubsub.on(event, () => log(`pubsub [${SUBJECT}]: event = ${event}`));
```
to:
```javascript
pubsub.fed.on(event, () => log(`pubsub [${SUBJECT}]: event = ${event}`));
```
and you should be set. I've tested it with you example and it seems to work.

**Comment by jokeyrhyme** [comment]
Really sorry for the late response.

Yes, I can confirm that this is working as you describe. Thanks so much for your efforts. :D
